name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main ] # or your default branch
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Build Next.js Static Site
        run: bun run build
      # Assuming your next.config.js is configured for static export
      # The output directory will be './out'

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: your-project-name # Replace with your Cloudflare Pages project name
          directory: out # The directory containing your static assets
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
